### PR TITLE
Pin rules_{cc,python} to specific commit

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@Yannic thank you for this. My thought would be to remain using the head and when bazel releases switch. What do you think?

**Comment by Yannic** [comment]
I think eventually pinning to the latest release of `rules_{cc,python}` makes sense. However, it's unclear when (or even if) these rules get releases, and I'd rather pin to the commit that gets tested by Travis than to select a random, potentially broken commit at runtime. 

Bazel 0.29.0 might be released today anyway https://github.com/bazelbuild/bazel/issues/8572#issuecomment-522613096.

**Comment by absl-federation-github** [comment]
@Yannic lets wait and see. If the 0.29.0 gets released please make changes to reflect that.
Also, the changes need to go into https://github.com/abseil/federation-head/blob/master/head_sync.py . This is the script that generates the daily releases on a schedule, so this PR should be limited to changed to https://github.com/abseil/federation-head/blob/master/head_sync.py that should get picked up on the next run

Thanks again
G

**Comment by Yannic** [comment]
@gennadiycivil Bazel 0.29 has been released: https://blog.bazel.build/2019/08/27/bazel-0.29.0.html

Still no releases for `rules_{cc,python}` in sight.

**Comment by derekmauro** [comment]
I'm only noticing this now. I just created https://github.com/abseil/federation-head/pull/156 for this, which is basically the same thing. It should have been done like this all along.

**Comment by Yannic** [comment]
Sure, thanks for updating this.
Closing in favor of #156.

**Pull request closed without merging**
